version: "3.9"

services:
  backend:
    build:
      context: .                # project root as build context
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data            # mount local data for dev
      - ./models:/models        # mount local models for dev
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
